version: "3.8"

services:
  postgres:
    image: postgres:14.10
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=${HOST}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "80:80"
    depends_on:
        - postgres
