// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_category))]
pub struct Category {
    pub id_category: i32,
    pub category_name: String,
    pub active: bool,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_day))]
pub struct Day {
    pub id_day: i32,
    pub day_name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_food_plan))]
pub struct FoodPlan {
    pub id_food_plan: i32,
    pub food_plan_name: String,
    pub description: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_food_plan_day))]
pub struct FoodPlanDay {
    pub id_food_plan_day: i32,
    pub id_food_plan: i32,
    pub id_day: i32,
    pub id_menu: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_food_plan_recipe))]
pub struct FoodPlanRecipe {
    pub id_food_plan_recipe: i32,
    pub id_recipe: i32,
    pub id_food_plan: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_ingredient))]
pub struct Ingredient {
    pub id_ingredient: i32,
    pub ingredient_name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_menu))]
pub struct Menu {
    pub id_menu: i32,
    pub menu_name: String,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Post {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub published: bool,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_recipe))]
pub struct Recipe {
    pub id_recipe: i32,
    pub recipe_name: String,
    pub id_category: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(id_recipe_ingredient))]
pub struct RecipeIngredient {
    pub id_recipe_ingredient: i32,
    pub id_ingredient: i32,
    pub id_recipe: i32,
}

